### ISSUE TITLE
feat: slash commands

### ISSUE THREAD

**Issue by KagChi** [KagChi/noteblock#11]
should slash commands added?

**Comment by BrianWasTaken** [comment]
yes.

**Comment by MahbodHastam** [comment]
Checkout [this](https://www.npmjs.com/package/discord-slash-commands-client) package.

**Comment by KagChi** [comment]
> Checkout [this](https://www.npmjs.com/package/discord-slash-commands-client) package.

is `discord-slash-commands-client` slash command builder?
we can use [this](https://www.npmjs.com/package/@discordjs/builders) package instead.

**Comment by KagChi** [comment]
this feature being worked on this [branch](https://github.com/KagChi/noteblock/pull/31)

**Comment by KagChi** [comment]
closing this issue because it has been merged in this [PR](https://github.com/KagChi/noteblock/pull/31)
