### ISSUE TITLE
question: lavalink server

### ISSUE THREAD

**Issue by BrianWasTaken** [KagChi/noteblock#22]
how do you even make your register a lavalink server? i couldn't find any tutorials on google.

**Comment by KagChi** [comment]
wdym "register" ?

**Comment by BrianWasTaken** [comment]
i mean, from what I see in your `index` file, in your root folder (on your `lavalink-repl` repository), is it also applicable on heroku?

**Comment by KagChi** [comment]
i have't tested on heroku.

**Comment by BrianWasTaken** [comment]
alright.
