### ISSUE TITLE
feat: Spotify playlist support

### ISSUE THREAD

**Issue by voidpls** [KagChi/noteblock#69]
Ability to get all the songs from a Spotify playlist.

Would this require a Spotify API key?

**Comment by KagChi** [comment]
this feature has been implemented, because of `better-erela.js-spotify` doesnt need any spotify api key

**Comment by voidpls** [comment]
I always get `⛔ | No result found.` when trying to queue a playlist. Can you recreate this?

**Comment by KagChi** [comment]
please provide spotify urls. i cant reproduce

**Comment by voidpls** [comment]
No specific URL, happened with all playlists with an error about failing to obtain a token or something. Fixed itself after a restart. I'll report full error if it happens again.
