### ISSUE TITLE
node main disconnected

### ISSUE THREAD

**Issue by mxxtthias** [KagChi/noteblock#8]
sometimes i got this error `[2021-04-18T06:35:14.587] [WARN] NOTEBLOCK - NODE [NODE-MAIN] DISCONNECTED` , any solution?

**Comment by Zelfy** [comment]
create your hosting of these files
>>https://github.com/KagChi/lavalink-repl
>> https://github.com/KagChi/lavalink-repl

**Comment by KagChi** [comment]
Sometimes replit restart their container
